name: js_wrapping
version: 0.7.4
description: That package contains elements to easilly wrap JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  js: ^0.6.3
